-- CREACION USUARIO MAESTRO (DBA) --

CREATE USER MAESTRO_PROYECTO IDENTIFIED BY Maestro1234567
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;
/
GRANT CREATE SESSION TO MAESTRO_PROYECTO;
GRANT CREATE TABLE TO MAESTRO_PROYECTO;
GRANT CREATE VIEW TO MAESTRO_PROYECTO;
GRANT CREATE PROCEDURE TO MAESTRO_PROYECTO;
GRANT CREATE USER TO MAESTRO_PROYECTO;
GRANT ALTER USER TO MAESTRO_PROYECTO;
GRANT DROP USER TO MAESTRO_PROYECTO;
GRANT CREATE ROLE TO MAESTRO_PROYECTO;
GRANT CREATE ANY TABLE TO MAESTRO_PROYECTO;
GRANT DROP ANY TABLE TO MAESTRO_PROYECTO;
GRANT SELECT ANY TABLE TO MAESTRO_PROYECTO;
GRANT INSERT ANY TABLE TO MAESTRO_PROYECTO;
GRANT UPDATE ANY TABLE TO MAESTRO_PROYECTO;
GRANT DELETE ANY TABLE TO MAESTRO_PROYECTO;
GRANT ALTER SYSTEM TO MAESTRO_PROYECTO;
GRANT UNLIMITED TABLESPACE TO MAESTRO_PROYECTO;
/ 
COMMIT;