-- Creación de roles con grants específicos
CREATE ROLE ADMIN_ROLE;
GRANT CREATE USER TO ADMIN_ROLE;
GRANT CREATE PROFILE TO ADMIN_ROLE;
GRANT CREATE TABLE TO ADMIN_ROLE;
GRANT CREATE VIEW TO ADMIN_ROLE;
GRANT CREATE SEQUENCE TO ADMIN_ROLE;
GRANT CREATE PROCEDURE TO ADMIN_ROLE;
GRANT CREATE TRIGGER TO ADMIN_ROLE;
GRANT CREATE SYNONYM TO ADMIN_ROLE;
GRANT CREATE MATERIALIZED VIEW TO ADMIN_ROLE;
GRANT CREATE ROLE TO ADMIN_ROLE;

-- Grants completos en todas las tablas
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_ESTADO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TIPO_USUARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_PAIS_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_PROVINCIA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CANTON_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_DISTRITO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_DIRECCION_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_USUARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CORREO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TELEFONO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CUENTA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TIPO_OTP_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CODIGO_OTP_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_REFRESH_TOKEN_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CATEGORIA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_PRODUCTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_INVENTARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TIPO_MOVIMIENTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_MOVIMIENTO_INVENTARIO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_VENTA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_VENTA_PRODUCTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_EVENTO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TIPO_CONTENIDO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CONTENIDO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TIPO_TICKET_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_EVENTO_TICKET TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TICKET_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_MONEDA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_FACTURA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_VENTA_FACTURA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_TICKET_FACTURA_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_PAGO_PAYPAL_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_SEASON_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_SEASON_SET_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_RED_SOCIAL_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CUENTA_RED_SOCIAL_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CARRITO_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CARRITO_ITEM_TB TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_AUDITORIA_TB TO ADMIN_ROLE;
/

CREATE ROLE DESAROLLADOR_ROLE;
-- Grants solo en tablas importantes: usuario, producto, venta, evento, cuenta
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_USUARIO_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_CUENTA_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_PRODUCTO_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_VENTA_TB TO DESAROLLADOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MAESTRO_PROYECTO.FIDE_EVENTO_TB TO DESAROLLADOR_ROLE;
/

CREATE ROLE ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_ESTADO_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_TIPO_USUARIO_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_USUARIO_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_CORREO_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_TELEFONO_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_CUENTA_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_CATEGORIA_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_PRODUCTO_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_VENTA_TB TO ANALISTA_ROLE;
GRANT SELECT ON MAESTRO_PROYECTO.FIDE_EVENTO_TB TO ANALISTA_ROLE;
/
