-- Creación de usuarios con roles específicos
CREATE USER ADMIN_DANCEROOM IDENTIFIED BY Admin1234567
DEFAULT TABLESPACE PROYECTO_TB
TEMPORARY TABLESPACE TEMP
PROFILE ADMIN_PROFILE
QUOTA UNLIMITED ON PROYECTO_TB;
/

GRANT CONNECT, RESOURCE TO ADMIN_DANCEROOM;
GRANT ADMIN_ROLE TO ADMIN_DANCEROOM;
/

-- Usuario DESAROLLADOR: Permisos para consultar y modificar datos (desarrollo)
CREATE USER DESAROLLADOR_DANCEROOM IDENTIFIED BY Desarollador1234567
DEFAULT TABLESPACE PROYECTO_TB
TEMPORARY TABLESPACE TEMP
PROFILE DESAROLLADOR_PROFILE
QUOTA 50M ON PROYECTO_TB;
/

GRANT CONNECT TO DESAROLLADOR_DANCEROOM;
GRANT DESAROLLADOR_ROLE TO DESAROLLADOR_DANCEROOM;
/

-- Usuario ANALISTA: Solo permisos de lectura (análisis)
CREATE USER ANALISTA_DANCEROOM IDENTIFIED BY Analista1234567
DEFAULT TABLESPACE PROYECTO_TB
TEMPORARY TABLESPACE TEMP
PROFILE ANALISTA_PROFILE
QUOTA 10M ON PROYECTO_TB;
/

GRANT CONNECT TO ANALISTA_DANCEROOM;
GRANT ANALISTA_ROLE TO ANALISTA_DANCEROOM;
/

COMMIT;


