-- CREACION USUARIO MAESTRO (DBA) --

CREATE USER MAESTRO_PROYECTO IDENTIFIED BY Maestro1234567
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO MAESTRO_PROYECTO;
GRANT CREATE TABLE TO MAESTRO_PROYECTO;
GRANT CREATE VIEW TO MAESTRO_PROYECTO;
GRANT CREATE USER TO MAESTRO_PROYECTO;
GRANT CREATE SEQUENCE TO MAESTRO_PROYECTO;
GRANT CREATE PROCEDURE TO MAESTRO_PROYECTO;
GRANT CREATE TRIGGER TO MAESTRO_PROYECTO;
GRANT CREATE SYNONYM TO MAESTRO_PROYECTO;
GRANT CREATE MATERIALIZED VIEW TO MAESTRO_PROYECTO;
GRANT CREATE ROLE TO MAESTRO_PROYECTO;
GRANT UNLIMITED TABLESPACE TO MAESTRO_PROYECTO;
GRANT CREATE PROFILE TO MAESTRO_PROYECTO;
COMMIT;
