-- CREACION USUARIO DANCEROOM (SCHEMA DUENO DEL PROYECTO) --

CREATE USER DANCEROOM
IDENTIFIED BY DbDance#2026Own
QUOTA 500M ON USERS;

GRANT CREATE SESSION TO DANCEROOM;
GRANT CREATE TABLE TO DANCEROOM;
GRANT CREATE VIEW TO DANCEROOM;
GRANT CREATE MATERIALIZED VIEW TO DANCEROOM;
GRANT CREATE SEQUENCE TO DANCEROOM;
GRANT CREATE PROCEDURE TO DANCEROOM;
GRANT CREATE TRIGGER TO DANCEROOM;

COMMIT;
