--VISTAS NORMALES

CREATE OR REPLACE VIEW FIDE_USUARIO_COMPLETO_V AS 
SELECT
    U.IDENTIFICACION,
    U.NOMBRE,
    U.APELLIDO_PATERNO,
    U.APELLIDO_MATERNO,
    U.FECHA_REGISTRO,
    TU.NOMBRE AS TIPO_USUARIO,
    C.CORREO,
    T.TELEFONO,
    E.NOMBRE_ESTADO AS ESTADO_USUARIO,
    D.CALLE || ' ' || D.NUMERO || ' , ' || DIST.NOMBRE || ' , ' || CAN.NOMBRE || ' , ' || PROV.NOMBRE AS DIRECCION_COMPLETA
FROM FIDE_USUARIO_TB U
LEFT JOIN FIDE_TIPO_USUARIO_TB tu ON u.ID_TIPO_USUARIO = tu.ID_TIPO_USUARIO
LEFT JOIN FIDE_CORREO_TB c ON u.IDENTIFICACION = c.IDENTIFICACION
LEFT JOIN FIDE_TELEFONO_TB t ON u.IDENTIFICACION = t.IDENTIFICACION
LEFT JOIN FIDE_DIRECCION_TB d ON u.ID_DIRECCION = d.ID_DIRECCION
LEFT JOIN FIDE_DISTRITO_TB dist ON d.ID_DISTRITO = dist.ID_DISTRITO
LEFT JOIN FIDE_CANTON_TB can ON dist.ID_CANTON = can.ID_CANTON
LEFT JOIN FIDE_PROVINCIA_TB prov ON can.ID_PROVINCIA = prov.ID_PROVINCIA
LEFT JOIN FIDE_ESTADO_TB e ON u.ID_ESTADO = e.ID_ESTADO;
/

CREATE OR REPLACE VIEW FIDE_CARRITO_ACTIVO_V AS
SELECT 
    ca.ID_CARRITO,
    ca.ID_CUENTA,
    cu.USUARIO,
    ci.ID_PRODUCTO,
    p.NOMBRE AS PRODUCTO_NOMBRE,
    p.PRECIO AS PRECIO_UNITARIO,
    ci.CANTIDAD,
    (ci.CANTIDAD * p.PRECIO) AS SUBTOTAL
FROM FIDE_CARRITO_TB ca
JOIN FIDE_CARRITO_ITEM_TB ci ON ca.ID_CARRITO = ci.ID_CARRITO
JOIN FIDE_PRODUCTO_TB p ON ci.ID_PRODUCTO = p.ID_PRODUCTO
JOIN FIDE_CUENTA_TB cu ON ca.ID_CUENTA = cu.ID_CUENTA
WHERE ca.ID_ESTADO = 1 
AND ci.ID_ESTADO = 1;   
/

CREATE OR REPLACE VIEW FIDE_EVENTOS_DISPONIBLES_V AS
SELECT 
    e.ID_EVENTO,
    e.TITULO,
    e.DESCRIPCION,
    e.FECHA_EVENTO,
    e.FLYER_URL,
    e.PRECIO AS PRECIO_BASE,
    tt.NOMBRE AS TIPO_TICKET,
    et.PRECIO AS PRECIO_TICKET,
    et.CUPOS_DISPONIBLES,
    (et.CUPOS_TOTALES - et.CUPOS_VENDIDOS) AS DISPONIBLES_REAL,
    d.CALLE || ', ' || dist.NOMBRE || ', ' || can.NOMBRE AS UBICACION_SIMPLE
FROM FIDE_EVENTO_TB e
JOIN FIDE_EVENTO_TICKET et ON e.ID_EVENTO = et.ID_EVENTO
JOIN FIDE_TIPO_TICKET_TB tt ON et.ID_TIPO_TICKET = tt.ID_TIPO_TICKET
LEFT JOIN FIDE_DIRECCION_TB d ON e.ID_DIRECCION = d.ID_DIRECCION
LEFT JOIN FIDE_DISTRITO_TB dist ON d.ID_DISTRITO = dist.ID_DISTRITO
LEFT JOIN FIDE_CANTON_TB can ON dist.ID_CANTON = can.ID_CANTON
WHERE e.ID_ESTADO = 1
AND et.ID_ESTADO = 1
AND et.FECHA_INICIO <= SYSDATE
AND et.FECHA_FIN >= SYSDATE
AND (et.CUPOS_TOTALES - et.CUPOS_VENDIDOS) > 0;
/

CREATE OR REPLACE VIEW FIDE_MIS_TICKETS_V AS
SELECT 
    t.ID_TICKET,
    t.CODIGO_QR,
    t.FECHA_GENERACION,
    e.TITULO AS EVENTO_TITULO,
    e.FECHA_EVENTO,
    tt.NOMBRE AS TIPO_TICKET,
    et.PRECIO,
    cu.USUARIO,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS NOMBRE_COMPLETO
FROM FIDE_TICKET_TB t
JOIN FIDE_EVENTO_TICKET et ON t.ID_EVENTO_TICKET = et.ID_EVENTO_TICKET
JOIN FIDE_EVENTO_TB e ON et.ID_EVENTO = e.ID_EVENTO
JOIN FIDE_TIPO_TICKET_TB tt ON et.ID_TIPO_TICKET = tt.ID_TIPO_TICKET
JOIN FIDE_CUENTA_TB cu ON t.ID_CUENTA = cu.ID_CUENTA
JOIN FIDE_USUARIO_TB u ON cu.IDENTIFICACION = u.IDENTIFICACION
WHERE t.ID_ESTADO = 1;
/

CREATE OR REPLACE VIEW FIDE_PRODUCTOS_STOCK_V AS
SELECT 
    p.ID_PRODUCTO,
    p.NOMBRE,
    p.DESCRIPCION,
    p.PRECIO,
    c.NOMBRE AS CATEGORIA,
    i.CANTIDAD AS STOCK_ACTUAL,
    e.NOMBRE_ESTADO AS ESTADO_PRODUCTO
FROM FIDE_PRODUCTO_TB p
JOIN FIDE_CATEGORIA_TB c ON p.ID_CATEGORIA = c.ID_CATEGORIA
LEFT JOIN FIDE_INVENTARIO_TB i ON p.ID_PRODUCTO = i.ID_PRODUCTO AND i.ID_ESTADO = 1
LEFT JOIN FIDE_ESTADO_TB e ON p.ID_ESTADO = e.ID_ESTADO
WHERE p.ID_ESTADO = 1;
/

CREATE OR REPLACE VIEW FIDE_HISTORIAL_COMPRAS_V AS
SELECT 
    v.ID_VENTA,
    v.FECHA_VENTA,
    v.TOTAL_VENTA,
    f.ID_FACTURA,
    f.TOTAL AS TOTAL_FACTURADO,
    f.FECHA_FACTURA,
    m.SIMBOLO AS MONEDA,
    cu.USUARIO,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS CLIENTE
FROM FIDE_VENTA_TB v
JOIN FIDE_VENTA_FACTURA_TB vf ON v.ID_VENTA = vf.ID_VENTA
JOIN FIDE_FACTURA_TB f ON vf.ID_FACTURA = f.ID_FACTURA
JOIN FIDE_MONEDA_TB m ON f.ID_MONEDA = m.ID_MONEDA
JOIN FIDE_CUENTA_TB cu ON v.ID_CUENTA = cu.ID_CUENTA
JOIN FIDE_USUARIO_TB u ON cu.IDENTIFICACION = u.IDENTIFICACION
WHERE v.ID_ESTADO = 1;
/

--VISTAS MATERIALIZADAS

CREATE MATERIALIZED VIEW FIDE_TOP_PRODUCTOS_VM
REFRESH COMPLETE ON DEMAND
AS
SELECT * FROM (
    SELECT 
        p.ID_PRODUCTO,
        p.NOMBRE,
        c.NOMBRE AS CATEGORIA,
        SUM(vp.CANTIDAD) AS TOTAL_UNIDADES_VENDIDAS,
        SUM(vp.TOTAL) AS TOTAL_VENDIDO_COLONES,
        COUNT(DISTINCT vp.ID_VENTA) AS NUMERO_VENTAS
    FROM FIDE_PRODUCTO_TB p
    JOIN FIDE_VENTA_PRODUCTO_TB vp ON p.ID_PRODUCTO = vp.ID_PRODUCTO
    JOIN FIDE_CATEGORIA_TB c ON p.ID_CATEGORIA = c.ID_CATEGORIA
    WHERE vp.ID_ESTADO = 1
    GROUP BY p.ID_PRODUCTO, p.NOMBRE, c.NOMBRE
    ORDER BY TOTAL_UNIDADES_VENDIDAS DESC
)
WHERE ROWNUM <= 10;
/

CREATE MATERIALIZED VIEW FIDE_VENTAS_MENSUALES_VM
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    EXTRACT(YEAR FROM v.FECHA_VENTA) AS ANIO,
    EXTRACT(MONTH FROM v.FECHA_VENTA) AS MES,
    TO_CHAR(v.FECHA_VENTA, 'YYYY-MM') AS ANIO_MES,
    COUNT(v.ID_VENTA) AS TOTAL_TRANSACCIONES,
    SUM(v.TOTAL_VENTA) AS INGRESOS_TOTALES,
    AVG(v.TOTAL_VENTA) AS TICKET_PROMEDIO
FROM FIDE_VENTA_TB v
WHERE v.ID_ESTADO = 1
GROUP BY EXTRACT(YEAR FROM v.FECHA_VENTA), EXTRACT(MONTH FROM v.FECHA_VENTA), TO_CHAR(v.FECHA_VENTA, 'YYYY-MM')
ORDER BY ANIO DESC, MES DESC;
/

CREATE MATERIALIZED VIEW FIDE_RECAUDACION_EVENTOS_VM
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    e.ID_EVENTO,
    e.TITULO,
    e.FECHA_EVENTO,
    COUNT(t.ID_TICKET) AS CANTIDAD_TICKETS_VENDIDOS,
    SUM(et.PRECIO) AS RECAUDACION_TOTAL,
    AVG(et.PRECIO) AS PRECIO_PROMEDIO_TICKET
FROM FIDE_EVENTO_TB e
JOIN FIDE_EVENTO_TICKET et ON e.ID_EVENTO = et.ID_EVENTO
JOIN FIDE_TICKET_TB t ON et.ID_EVENTO_TICKET = t.ID_EVENTO_TICKET
WHERE t.ID_ESTADO = 1
AND et.ID_ESTADO = 1
GROUP BY e.ID_EVENTO, e.TITULO, e.FECHA_EVENTO
ORDER BY RECAUDACION_TOTAL DESC;
/

CREATE MATERIALIZED VIEW FIDE_INVENTARIO_VALORIZADO_VM
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    p.ID_PRODUCTO,
    p.NOMBRE,
    c.NOMBRE AS CATEGORIA,
    i.CANTIDAD AS STOCK_ACTUAL,
    p.PRECIO AS PRECIO_UNITARIO,
    (i.CANTIDAD * p.PRECIO) AS VALOR_TOTAL_INVENTARIO
FROM FIDE_PRODUCTO_TB p
JOIN FIDE_CATEGORIA_TB c ON p.ID_CATEGORIA = c.ID_CATEGORIA
JOIN FIDE_INVENTARIO_TB i ON p.ID_PRODUCTO = i.ID_PRODUCTO
WHERE i.ID_ESTADO = 1
AND p.ID_ESTADO = 1
ORDER BY VALOR_TOTAL_INVENTARIO DESC;
/

CREATE MATERIALIZED VIEW FIDE_TOP_CLIENTES_VM
REFRESH COMPLETE ON DEMAND
AS
SELECT * FROM (
    SELECT 
        u.IDENTIFICACION,
        u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS NOMBRE_COMPLETO,
        cu.USUARIO,
        COUNT(v.ID_VENTA) AS TOTAL_COMPRAS,
        SUM(v.TOTAL_VENTA) AS TOTAL_GASTADO,
        MAX(v.FECHA_VENTA) AS ULTIMA_COMPRA
    FROM FIDE_USUARIO_TB u
    JOIN FIDE_CUENTA_TB cu ON u.IDENTIFICACION = cu.IDENTIFICACION
    JOIN FIDE_VENTA_TB v ON cu.ID_CUENTA = v.ID_CUENTA
    WHERE v.ID_ESTADO = 1
    GROUP BY u.IDENTIFICACION, u.NOMBRE, u.APELLIDO_PATERNO, cu.USUARIO
    ORDER BY TOTAL_GASTADO DESC
)
WHERE ROWNUM <= 10;
/

CREATE MATERIALIZED VIEW FIDE_FACTURACION_MENSUAL_VM
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    EXTRACT(YEAR FROM f.FECHA_FACTURA) AS ANIO,
    EXTRACT(MONTH FROM f.FECHA_FACTURA) AS MES,
    COUNT(f.ID_FACTURA) AS TOTAL_FACTURAS,
    SUM(f.SUBTOTAL) AS TOTAL_SUBTOTAL,
    SUM(f.IMPUESTO) AS TOTAL_IMPUESTOS,
    SUM(f.TOTAL) AS TOTAL_FACTURADO
FROM FIDE_FACTURA_TB f
WHERE f.ID_ESTADO = 1
GROUP BY EXTRACT(YEAR FROM f.FECHA_FACTURA), EXTRACT(MONTH FROM f.FECHA_FACTURA)
ORDER BY ANIO DESC, MES DESC;
/